spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/insurance_app
    username:  ${DB_USER}
    password:  ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      max-lifetime: 1800000 #30min

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration
